### ISSUE TITLE
Getter 'uid' was called on null

### ISSUE THREAD

**Issue by abhimanyunaikare** [tapanrgohil/firebase_phone_bloc#1]
such Method Error
Tried  calling: uid

After mobile number is entered and  on submit error screen appears red

Error log:
I/flutter ( 7682): SendOtpEvent
I/flutter ( 7682): Transition { currentState: InitialLoginState, event: SendOtpEvent, nextState: LoadingState }
I/BiChannelGoogleApi( 7682): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@9f68bde
I/flutter ( 7682): OtpSendEvent
I/flutter ( 7682): OtpSendEvent
I/flutter ( 7682): Transition { currentState: LoadingState, event: OtpSendEvent, nextState: OtpSentState }
W/table_app_fres( 7682): Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
W/table_app_fres( 7682): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
I/flutter ( 7682): LoginCompleteEvent
I/flutter ( 7682): LoginCompleteEvent
I/flutter ( 7682): Transition { currentState: OtpSentState, event: LoginCompleteEvent, nextState: LoginCompleteState }

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building BlocBuilder<LoginBloc, LoginState>(dirty, state: _BlocBuilderBaseState<LoginBloc, LoginState>#572cb):
The getter 'uid' was called on null.
Receiver: null
Tried calling: uid

The relevant error-causing widget was: 
  BlocBuilder<LoginBloc, LoginState> file:///home/abhimanyu/AndroidStudioProjects/vegetable_app_fresh/lib/login/login_page.dart:70:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _LoginFormState.getViewAsPerState (package:vegetable_app_fresh/login/login_page.dart:115:48)
#2      _LoginFormState.build.<anonymous closure> (package:vegetable_app_fresh/login/login_page.dart:87:36)
#3      BlocBuilder.build (package:flutter_bloc/src/bloc_builder.dart:90:57)
#4      _BlocBuilderBaseState.build (package:flutter_bloc/src/bloc_builder.dart:162:48)

**Comment by RahulKandoriya** [comment]
I also encountered the same problem and came up with the workaround.

it just needs to be added one line of code.

in file login_bloc.dart

instead of 

final PhoneCodeSent = (String verId, [int forceResent]) {
      this.verID = verId;
      eventStream.add(OtpSendEvent());
};

it should be 

final PhoneCodeSent = (String verId, [int forceResent]) {
      this.verID = verId;
      eventStream.add(OtpSendEvent());
      //add below line
      eventStream.close();
};

**Comment by tapanrgohil** [comment]
@RahulKandoriya Thanks for the response.
@abhimanyunaikare can you check if it is working for you? So we can close this issue
